name: DragonBotBridge
version: ${project.version}
main: pl.dcbot.DragonBotBridge
api-version: 1.20
commands:
  zglos:
    description: Zglos gracza lub problem
  discord:
    description: Zglos gracza lub problem
  dclink:
    description: Zglos gracza lub problem
  przeniesrange:
    description: Przenies range
  anulujprzenoszenie:
    description: anuluje
  pluginmsgtest:
    description: test